#Arguments needed by main.py
scenario: Warehouse #name of the folder inside scenarios

model_config_file: maddpg.json
model_file: maddpg.th

actor_file: rnn_agent
actor_class: RNNAgent

env_file: warehouse
env_class: Warehouse #This needs to have all of the functionalities of a gym to work
n_actions: 5 #The number of actions available for the agent
episodes: 10 #Number of episodes to run for
n_agents: 6
shared_reward: False

#Arguments needed by the environment
LEFT: -1.40
RIGHT: 1.40
UP: -0.9
DOWN: 0.9
MIN_DIST : 0.2 #This should probably be renamed. This is actually the amount of distance the robots move per time step...
START_DIST: .6 #Minimum distance the agents start from each other
load_reward: 1
unload_reward: 3
goal_width: .5
num_robots: 6
show_figure_frequency: -1 #Set to -1 to turn off figures. Needs to be 1 when submitting to Robotarium
real_time: False
delta: 0.0 #If > 0, make sure that the agent can handle changing observation sizes
num_neighbors: 5
max_episode_steps: 100
update_frequency: 34
robotarium: False #Should be False during training to speed up robots, needs to be true when submitting
