#Arguments needed by main.py
scenario: ArcticTransport #name of the folder inside scenarios

model_config_file: mappo_full.json
model_file: mappo_full.th

actor_file: rnn_agent
actor_class: RNNAgent

env_file: ArcticTransport
env_class: ArcticTransport #This needs to have all of the functionalities of a gym to work
n_actions: 5 #The number of actions available for the agent
episodes: 30 #Number of episodes to run for
n_agents: 4
shared_reward: True

seed: -1 #sets the seed. Set to -1 to use a random seed.

show_figure_frequency: -1 #Set to -1 to turn off figures. Needs to be 1 when submitting to Robotarium
real_time: False
max_episode_steps: 60
update_frequency: 36
robotarium: False #Should be False during training to speed up robots, needs to be true when submitting
barrier_certificate: safe #Can be safe or default for strong or weak barrier certificates
penalize_violations: True #If true, agents get a negative reward for collisions or boundary infractions and the episode stops

#Arguments needed by this scenario
LEFT: -1.40
RIGHT: 1.40
UP: -0.9
DOWN: 0.9
normal_step : 0.2 #This should probably be renamed. This is actually the amount of distance the robots move per time step...
fast_step: 0.3
slow_step: 0.1
not_reached_penalty: -0.05
dist_multiplier: -0.075


